"""Fetch ward zoning data from the Chicago Cityscape Zoning Explorer API.

Calls the API for all 50 Chicago wards, computes RS-zoned land percentages,
and writes the results to app/data/ward_zoning_data.py as a Python dict literal.

Requires CHICAGO_CITYSCAPE_API_KEY to be set in the environment or .env file.

Usage:
    python -m scripts.fetch_ward_zoning_data
"""

import asyncio
import logging
from datetime import datetime, timezone
from pathlib import Path

import aiohttp

from app.core.config import settings
from app.imports.sources.ward_zoning import compute_rs_percentage

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("fetch-ward-zoning")

API_BASE_URL = "https://chicagocityscape.com/api/zoningexplorer.php"
TOTAL_WARDS = 50
MAX_CONCURRENT = 5

OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent / "app" / "data" / "ward_zoning_data.py"
)


async def fetch_ward_zoning(
    session: aiohttp.ClientSession,
    semaphore: asyncio.Semaphore,
    api_key: str,
    ward: int,
) -> tuple[int, float | None]:
    """Fetch zoning data for a single ward and compute RS%."""
    async with semaphore:
        params = {
            "key": api_key,
            "endpoint": "assessment",
            "place": f"ward-{ward}",
        }
        try:
            async with session.get(API_BASE_URL, params=params) as resp:
                if resp.status != 200:
                    logger.warning("Ward %d: HTTP %d", ward, resp.status)
                    return ward, None
                body = await resp.json()
                if not body.get("success", True):
                    logger.warning(
                        "Ward %d: API error: %s",
                        ward,
                        body.get("message", "unknown"),
                    )
                    return ward, None
                zone_data = body.get("data", [])
                rs_pct = compute_rs_percentage(zone_data)
                logger.info("Ward %d: RS-zoned %.1f%%", ward, rs_pct)
                return ward, rs_pct
        except Exception:
            logger.exception("Ward %d: request failed", ward)
            return ward, None


def write_data_module(data: dict[int, float]) -> None:
    """Write the ward RS% data as a Python module."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")
    lines = [
        "# Auto-generated by scripts/fetch_ward_zoning_data.py",
        "# Source: Chicago Cityscape Zoning Explorer API",
        f"# Generated: {timestamp}",
        "WARD_RS_ZONED_PCT: dict[int, float] = {",
    ]
    for ward in sorted(data):
        lines.append(f"    {ward}: {data[ward]},")
    lines.append("}")
    lines.append("")
    OUTPUT_PATH.write_text("\n".join(lines))
    logger.info("Wrote %d wards to %s", len(data), OUTPUT_PATH)


async def main() -> None:
    api_key = settings.CHICAGO_CITYSCAPE_API_KEY
    if not api_key:
        logger.error(
            "CHICAGO_CITYSCAPE_API_KEY is not set. "
            "Set it in your .env file or environment, then re-run."
        )
        return

    semaphore = asyncio.Semaphore(MAX_CONCURRENT)
    results: dict[int, float] = {}

    async with aiohttp.ClientSession() as session:
        tasks = [
            fetch_ward_zoning(session, semaphore, api_key, ward)
            for ward in range(1, TOTAL_WARDS + 1)
        ]
        for ward, rs_pct in await asyncio.gather(*tasks):
            if rs_pct is not None:
                results[ward] = rs_pct
            else:
                logger.warning("Ward %d: skipped (no data)", ward)

    if results:
        write_data_module(results)
    else:
        logger.error("No ward data fetched. Output file not written.")


if __name__ == "__main__":
    asyncio.run(main())
