"""Fetch IL scorecard data from OpenStates and write it to app/data/il_scorecard_data.py.

Calls the OpenStates API for each IL bill defined in ALL_IL_SCORECARD_PROJECTS,
extracts sponsorship or vote data, and writes a static Python module with the
results.

Run this script manually whenever the IL scorecard project definitions change
or when you want to refresh sponsorship/vote data:

    python -m scripts.fetch_openstates_il_scorecard_data

The generated file (app/data/il_scorecard_data.py) should be committed to the
repository so that import_scorecard_projects.py works without network access.
"""

import asyncio
import logging
from datetime import datetime, timezone
from pathlib import Path

from app.core.config import settings
from app.imports.sources.openstates import (
    IL_JURISDICTION_ID,
    OpenStateBillsClient,
    normalize_il_name,
    openstates_vote_option_to_status,
)
from app.models.pydantic.models import EntityStatus
from scripts.import_scorecard_projects import ALL_IL_SCORECARD_PROJECTS

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("fetch-openstates-il-scorecard")

MAX_CONCURRENT = 1
IL_SESSION = "104th"

OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent / "app" / "data" / "il_scorecard_data.py"
)


async def fetch_bill_data(
    semaphore: asyncio.Semaphore,
    client: OpenStateBillsClient,
    bill_identifier: str,
    import_type: str,
) -> tuple[str, str, dict | None]:
    """Fetch a single IL bill and return (bill_identifier, import_type, bill_dict)."""
    include = "sponsorships" if import_type == "sponsorship" else "votes"
    async with semaphore:
        try:
            logger.debug("Fetching %s %s=%s", bill_identifier, import_type, include)
            bill = await client.get_bill(
                session=IL_SESSION,
                bill_identifier=bill_identifier,
                jurisdiction_id=IL_JURISDICTION_ID,
                include=include,
            )
            if bill is not None:
                logger.info("Fetched %s (%s)", bill_identifier, import_type)
            else:
                logger.warning(
                    "No data returned for %s (%s)", bill_identifier, import_type
                )
            # Respect OpenStates rate limits: 7 second delay keeps us well under 10/min
            await asyncio.sleep(7)
            return bill_identifier, import_type, bill
        except Exception:
            logger.exception("Failed to fetch %s (%s)", bill_identifier, import_type)
            await asyncio.sleep(7)
            return bill_identifier, import_type, None


def extract_il_lookup(
    bill: dict,
    import_type: str,
    base_slug: str,
    chamber: str = "",
) -> dict[str, str]:
    """Extract a {normalized_name: entity_status_value} dict from a bill."""
    client = OpenStateBillsClient(api_key="")  # api_key not needed for extraction
    if import_type == "vote":
        preferred = "upper" if chamber == "senate" else "lower" if chamber == "house" else None
        votes = client.extract_votes(bill, preferred_classification=preferred)
        if votes is None:
            logger.warning("No vote data found for %s", base_slug)
            return {}
        result: dict[str, str] = {}
        for v in votes:
            voter = v.get("voter") or {}
            name = voter.get("name") or ""
            if not name:
                continue
            option = str(v.get("option", ""))
            status = openstates_vote_option_to_status(option)
            result[normalize_il_name(name)] = status.value
        return result
    else:
        # sponsorship: both primary and cosponsor → SOLID_APPROVAL
        sponsors = client.extract_sponsors(bill)
        result = {}
        for s in sponsors:
            person = s.get("person") or {}
            name = person.get("name") or ""
            if not name:
                continue
            result[normalize_il_name(name)] = EntityStatus.SOLID_APPROVAL.value
        return result


def write_il_data_module(data: dict[str, dict[str, str]]) -> None:
    """Write the IL scorecard lookup data as a Python module."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")
    lines = [
        "# -*- coding: utf-8 -*-",
        "# Auto-generated by scripts/fetch_openstates_il_scorecard_data.py",
        "# Source: OpenStates API",
        f"# Generated: {timestamp}",
        "IL_SCORECARD_DATA: dict[str, dict[str, str]] = {",
    ]
    for base_slug in sorted(data):
        lines.append(f'    "{base_slug}": {{')
        for name, status in sorted(data[base_slug].items()):
            lines.append(f'        "{name}": "{status}",')
        lines.append("    },")
    lines.append("}")
    lines.append("")
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote %d projects to %s", len(data), OUTPUT_PATH)


async def main() -> None:
    api_key = settings.OPENSTATES_API_KEY
    if not api_key:
        raise ValueError(
            "OPENSTATES_API_KEY is not set. "
            "Set it in your environment or .env file before running this script."
        )

    client = OpenStateBillsClient(api_key=api_key)
    semaphore = asyncio.Semaphore(MAX_CONCURRENT)

    logger.info(
        "Fetching %d IL bill(s) from OpenStates (session=%s)",
        len(ALL_IL_SCORECARD_PROJECTS),
        IL_SESSION,
    )

    tasks = [
        fetch_bill_data(
            semaphore,
            client,
            str(project_def["bill_identifier"]),
            str(project_def["import_type"]),
        )
        for project_def in ALL_IL_SCORECARD_PROJECTS
    ]

    # Map (bill_identifier, import_type) → bill dict
    bill_cache: dict[tuple[str, str], dict] = {}
    for bill_identifier, import_type, bill_data in await asyncio.gather(*tasks):
        if bill_data is not None:
            bill_cache[(bill_identifier, import_type)] = bill_data
        else:
            logger.warning("Skipping %s (%s) — no data", bill_identifier, import_type)

    result: dict[str, dict[str, str]] = {}
    for project_def in ALL_IL_SCORECARD_PROJECTS:
        base_slug = str(project_def["base_slug"])
        bill_identifier = str(project_def["bill_identifier"])
        import_type = str(project_def["import_type"])

        bill = bill_cache.get((bill_identifier, import_type))
        if bill is None:
            logger.warning("No bill data for %s; storing empty dict", base_slug)
            result[base_slug] = {}
            continue

        chamber = str(project_def.get("chamber", ""))
        lookup = extract_il_lookup(bill, import_type, base_slug, chamber=chamber)
        logger.info("Project %s: %d entries", base_slug, len(lookup))
        result[base_slug] = lookup

    if result:
        write_il_data_module(result)
    else:
        logger.error("No data fetched. Output file not written.")


if __name__ == "__main__":
    asyncio.run(main())
