"""Fetch ELMS scorecard data and write it to app/data/elms_scorecard_data.py.

Calls the Chicago City Clerk eLMS API for each matter defined in
ALL_SCORECARD_PROJECTS, extracts vote or sponsorship data, and writes a
static Python module with the results.

Run this script manually whenever the scorecard project definitions change
or when you want to refresh historical vote/sponsorship data:

    python -m scripts.fetch_elms_scorecard_data

The generated file (app/data/elms_scorecard_data.py) should be committed
to the repository so that import_scorecard_projects.py works without
network access.
"""

import asyncio
import logging
from datetime import datetime, timezone
from pathlib import Path

import aiohttp

from app.imports.sources.chicago_city_clerk_elms import (
    ELMSClient,
    normalize_name,
    vote_value_to_entity_status,
)
from app.models.pydantic.models import EntityStatus
from scripts.import_scorecard_projects import ALL_SCORECARD_PROJECTS

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("fetch-elms-scorecard")

MAX_CONCURRENT = 3

OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent / "app" / "data" / "elms_scorecard_data.py"
)


async def fetch_matter_data(
    session: aiohttp.ClientSession,
    semaphore: asyncio.Semaphore,
    matter_guid: str,
) -> tuple[str, dict | None]:
    """Fetch a single matter from ELMS and return (matter_guid, matter_dict)."""
    client = ELMSClient()
    async with semaphore:
        try:
            # ELMSClient opens its own session per call; pass session directly
            url = f"{client.base_url}/matter/{matter_guid}"
            logger.debug("Fetching matter %s", matter_guid)
            async with session.get(url) as response:
                if response.status == 404:
                    logger.warning("Matter not found: %s", matter_guid)
                    return matter_guid, None
                response.raise_for_status()
                data = await response.json(content_type=None)
                logger.info("Fetched matter %s", matter_guid)
                return matter_guid, data
        except Exception:
            logger.exception("Failed to fetch matter %s", matter_guid)
            return matter_guid, None


def extract_lookup(
    matter: dict,
    import_type: str,
    base_slug: str,
) -> dict[str, str]:
    """Extract a {normalized_name: entity_status_value} dict from a matter."""
    client = ELMSClient()
    if import_type == "vote":
        votes = client.extract_votes(matter)
        if votes is None:
            logger.warning("No final passage vote found for %s", base_slug)
            return {}
        return {
            normalize_name(str(v["voterName"])): vote_value_to_entity_status(
                str(v.get("vote", ""))
            ).value
            for v in votes
            if v.get("voterName")
        }
    else:
        # sponsorship
        sponsors = client.extract_sponsors(matter)
        return {
            normalize_name(str(s["sponsorName"])): EntityStatus.SOLID_APPROVAL.value
            for s in sponsors
            if s.get("sponsorName")
        }


def write_data_module(data: dict[str, dict[str, str]]) -> None:
    """Write the scorecard lookup data as a Python module."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")
    lines = [
        "# Auto-generated by scripts/fetch_elms_scorecard_data.py",
        "# Source: Chicago City Clerk eLMS API",
        f"# Generated: {timestamp}",
        "ELMS_SCORECARD_DATA: dict[str, dict[str, str]] = {",
    ]
    for base_slug in sorted(data):
        lines.append(f'    "{base_slug}": {{')
        for name, status in sorted(data[base_slug].items()):
            lines.append(f'        "{name}": "{status}",')
        lines.append("    },")
    lines.append("}")
    lines.append("")
    OUTPUT_PATH.write_text("\n".join(lines))
    logger.info("Wrote %d projects to %s", len(data), OUTPUT_PATH)


async def main() -> None:
    # Collect unique matter GUIDs and which projects reference each
    matter_to_projects: dict[str, list[dict]] = {}
    for project_def in ALL_SCORECARD_PROJECTS:
        guid = str(project_def["matter_guid"])
        matter_to_projects.setdefault(guid, []).append(project_def)

    logger.info(
        "Fetching %d unique matter(s) for %d project(s)",
        len(matter_to_projects),
        len(ALL_SCORECARD_PROJECTS),
    )

    semaphore = asyncio.Semaphore(MAX_CONCURRENT)
    matter_cache: dict[str, dict] = {}

    async with aiohttp.ClientSession() as session:
        tasks = [
            fetch_matter_data(session, semaphore, guid) for guid in matter_to_projects
        ]
        for matter_guid, matter_data in await asyncio.gather(*tasks):
            if matter_data is not None:
                matter_cache[matter_guid] = matter_data
            else:
                logger.warning("Skipping matter %s (no data)", matter_guid)

    result: dict[str, dict[str, str]] = {}
    for project_def in ALL_SCORECARD_PROJECTS:
        base_slug = str(project_def["base_slug"])
        guid = str(project_def["matter_guid"])
        import_type = str(project_def["import_type"])

        matter = matter_cache.get(guid)
        if matter is None:
            logger.warning("No matter data for %s; storing empty dict", base_slug)
            result[base_slug] = {}
            continue

        lookup = extract_lookup(matter, import_type, base_slug)
        logger.info("Project %s: %d entries", base_slug, len(lookup))
        result[base_slug] = lookup

    if result:
        write_data_module(result)
    else:
        logger.error("No data fetched. Output file not written.")


if __name__ == "__main__":
    asyncio.run(main())
